server.port=8082
spring.application.name=user-management-service
spring.datasource.url=jdbc:mysql://localhost:3306/user_management_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
spring.cloud.compatibility-verifier.enabled=false
auth.service.url=http://AUTH-SERVICE
logging.level.tn.esprit.usermanagementservice.client.AuthServiceClient=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
keycloak.realm=myapp2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:6083/realms/myapp2
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# WebSocket
spring.websocket.enabled=true







# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seddik202209@gmail.com
spring.mail.password=dzddwbrqxfdupgpk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true